server:
  port: 8080

spring:
  application:
    name: resource-service

  datasource:
    url: jdbc:postgresql://localhost:5432/resource-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

song-service:
  base-url: http://localhost:8082